name: flutter_login_demo
display: Personal finance
description: Personal finance will help you grow rich to fast.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: assets/piggy-bank.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/piggy-bank.png
